package dewadw.zzzb;

/* This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int module_scope = 2130771968;
    }

    public static final class color {
        public static final int black = 2130837504;
        public static final int purple_200 = 2130837505;
        public static final int purple_500 = 2130837506;
        public static final int purple_700 = 2130837507;
        public static final int teal_200 = 2130837508;
        public static final int teal_700 = 2130837509;
        public static final int white = 2130837510;
    }

    public static final class drawable {
        public static final int $ic_launcher_foreground__0 = 2130903040;
        public static final int ic_launcher_background = 2130903041;
        public static final int ic_launcher_foreground = 2130903042;
    }

    public static final class mipmap {
        public static final int ic_launcher = 2130968576;
        public static final int ic_launcher_round = 2130968577;
    }

    public static final class string {
        public static final int app_name = 2131034112;
    }
}
